[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[build]/recipes/recipes/celab.py\", line 68, in RunSteps",
      "    compile_failure = _RunStepsChromium(api)",
      "  File \"RECIPE_REPO[build]/recipes/recipes/celab.py\", line 122, in _RunStepsChromium",
      "    raise ValueError('Chromium bots must define `tests`.')",
      "ValueError('Chromium bots must define `tests`.')"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('Chromium bots must define `tests`.')"
    },
    "name": "$result"
  }
]