[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[build]/recipes/recipes/celab.py\", line 69, in RunSteps",
      "    raise ValueError(",
      "ValueError('Invalid `project`. Accepted values: celab, chromium, chrome.')"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('Invalid `project`. Accepted values: celab, chromium, chrome.')"
    },
    "name": "$result"
  }
]