[
  {
    "cmd": [
      "python",
      "-u",
      "None/testing/scripts/script.py",
      "--build-config-fs",
      "Release",
      "--paths",
      "{\"checkout\": \"None\", \"runit.py\": \"RECIPE_REPO[build]/scripts/tools/runit.py\", \"runtest.py\": \"RECIPE_REPO[build]/scripts/slave/runtest.py\"}",
      "--properties",
      "{\"bot_id\": \"fake-bot-id\", \"buildername\": \"test_buildername\", \"buildnumber\": 571, \"mastername\": \"test_group\", \"slavename\": \"fake-bot-id\", \"target_platform\": \"linux\"}",
      "--args",
      "[\"some\", \"args\"]",
      "run",
      "--output",
      "/path/to/tmp/json"
    ],
    "name": "script_test",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@json.output@{}@@@",
      "@@@STEP_LOG_END@json.output@@@"
    ]
  },
  {
    "cmd": [
      "python",
      "-u",
      "import sys; sys.exit(1)"
    ],
    "name": "script_test with suffix  had an invalid result",
    "~followup_annotations": [
      "@@@STEP_TEXT@The recipe expected the result to contain the key 'failures'. Contents are:<br/>{}@@@",
      "@@@STEP_FAILURE@@@"
    ]
  },
  {
    "cmd": [],
    "name": "details",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@details@compile_targets: ['other_target']@@@",
      "@@@STEP_LOG_LINE@details@uses_local_devices: False@@@",
      "@@@STEP_LOG_END@details@@@"
    ]
  },
  {
    "failure": {
      "failure": {},
      "humanReason": "Step('script_test with suffix  had an invalid result') (retcode: 1)"
    },
    "name": "$result"
  }
]